config/routes.rb
Rails.application.routes.draw do
  resources :as
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/a.rb
class A < ApplicationRecord
  after_create :associate_w_all_bs

  has_many :as_bs, dependent: :destroy
  has_many :bs, through: :as_bs

  private

    def associate_w_all_bs
      B.all.each do |b|
        bs << b
      end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/as_b.rb
class AsB < ApplicationRecord
  belongs_to :a
  belongs_to :b
end

app/models/b.rb
class B < ApplicationRecord
  has_many :as_bs
  has_many :as, through: :as_bs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/as_controller.rb
class AsController < ApplicationController
  before_action :set_a, only: [:show, :edit, :update, :destroy]

  # GET /as
  # GET /as.json
  def index
    @as = A.all
  end

  # GET /as/1
  # GET /as/1.json
  def show
  end

  # GET /as/new
  def new
    @a = A.new
  end

  # GET /as/1/edit
  def edit
  end

  # POST /as
  # POST /as.json
  def create
    @a = A.new(a_params)

    respond_to do |format|
      if @a.save
        format.html { redirect_to @a, notice: 'A was successfully created.' }
        format.json { render :show, status: :created, location: @a }
      else
        format.html { render :new }
        format.json { render json: @a.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /as/1
  # PATCH/PUT /as/1.json
  def update
    respond_to do |format|
      if @a.update(a_params)
        format.html { redirect_to @a, notice: 'A was successfully updated.' }
        format.json { render :show, status: :ok, location: @a }
      else
        format.html { render :edit }
        format.json { render json: @a.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /as/1
  # DELETE /as/1.json
  def destroy
    @a.destroy
    respond_to do |format|
      format.html { redirect_to as_url, notice: 'A was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_a
      @a = A.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def a_params
      params.require(:a).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/as_helper.rb
module AsHelper
end

app/views/as/_form.html.erb
<%= form_with(model: a, local: true) do |form| %>
  <% if a.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(a.errors.count, "error") %> prohibited this a from being saved:</h2>

      <ul>
      <% a.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/as/edit.html.erb
<h1>Editing A</h1>

<%= render 'form', a: @a %>

<%= link_to 'Show', @a %> |
<%= link_to 'Back', as_path %>

app/views/as/index.html.erb
<p id="notice"><%= notice %></p>

<h1>As</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @as.each do |a| %>
      <tr>
        <td><%= a.name %></td>
        <td><%= link_to 'Show', a %></td>
        <td><%= link_to 'Edit', edit_a_path(a) %></td>
        <td><%= link_to 'Destroy', a, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New A', new_a_path %>

app/views/as/new.html.erb
<h1>New A</h1>

<%= render 'form', a: @a %>

<%= link_to 'Back', as_path %>

app/views/as/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @a.name %>
</p>

<%= link_to 'Edit', edit_a_path(@a) %> |
<%= link_to 'Back', as_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sandbox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>